### ISSUE TITLE
Xml documentation is missing for imported symbols in Roslyn Projects

### ISSUE THREAD

**Issue by vladimirKa002** [phmonte/Buildalyzer#246]
Hello. I need to extract Xml documentation from all `ISymbols`. For this, I run this code to create a Roslyn Project and start its analysis:

```
AnalyzerManager manager = new AnalyzerManager();
IProjectAnalyzer analyzer = manager.GetProject(projectPath);
AdhocWorkspace workspace = new AdhocWorkspace();
Project project = analyzer.AddToWorkspace(workspace);

Compilation compilation = project.GetCompilationAsync().Result;

// ... For each document in project.Documents
var syntaxTree = document.GetSyntaxTreeAsync().Result;
var semanticModel = compilation.GetSemanticModel(syntaxTree, true);

// ... Get some symbol from syntaxtree using semanticmodel and extract Xml
var xml = symbol.GetDocumentationCommentXml(expandIncludes: true);
```
I can normally obtain Xml documentation for symbols declared inside the project.

However, no documentation is available for symbols loaded from imported packages. For example, if my analyser meets `List` symbol, it does not have Xml comment despite it is imported properly in analysed code.

Could you please advise do I miss anything in my code or maybe my Project loading stage is wrong?

**Comment by Corniel** [comment]
So, If I understand you correctly, you receive the XML-comments from your own code, but not from referenced code?

**Comment by phmonte** [comment]
Hello @vladimirKa002, I believe I understand what you mean, I was curious and did some local tests, I really didn't find a way that works.
Looking at swashbuckle it seems to me (I'm not sure) that it works because it reads the XML file from the repository, it would be an alternative to a "controlled" external reference where you have access to the XML, but you would have to code something to do this.
I found [this ](https://github.com/dotnet/roslyn/issues/23673)discussion that seems to be the same topic we are talking about here.

**Comment by oldominion** [comment]
Also experiencing this issue. Inspecting the generate code via solution explorer, the results of documentationCommentXml are correct, and I can use them to e.g. clone a method summary to a generated method wrapper class, and the IDE will show the intellisense correctly on the wrapped class, but at runtime documentationCommentXml returns empty so I can't provide the summary value in a return type of the wrapper method.
